---
- name: Create node_exporter system user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /usr/sbin/nologin
    create_home: false
  when: monitoring_node_exporter | bool

- name: Download node_exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ monitoring_node_exporter_version }}/node_exporter-{{ monitoring_node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: "0644"
  when: monitoring_node_exporter | bool

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: true
    extra_opts: [--strip-components=1, --wildcards, "*/node_exporter"]
  when: monitoring_node_exporter | bool

- name: Deploy node_exporter service
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target
      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure
      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  when: monitoring_node_exporter | bool
  notify: reload systemd

- name: Enable node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
  when: monitoring_node_exporter | bool
