---
- name: Configure systemd-resolved
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/softage.conf
    mode: "0644"
  notify: restart resolved

- name: Ensure resolved drop-in dir exists
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"
